language: python
python:
  - "2.7"
sudo: required
dist: trusty

install: 
  - sudo pip install -r requirements.txt

script:
  - cd module
  - python test.py 123 asdf

branches:
  only:
  - master
  - develop

notifications:
  email:
    recipients:
    - xukailu@baidu.com
    on_success: change
    on_failure: always
