language: python
python:
  - "2.7"
cache: ccache
sudo: required
dist: trusty

install
  - pip install MySQLdb

script:
  - PATH=/usr/local/bin:$PATH
  - |
    #export PATH=/home/scmtools/cmake-3.2.2/bin/:$PATH
    export ANAKIN_ROOT=`pwd`
    cd module
    python test.py 123 asdf

branches:
  only:
  - master
  - develop

notifications:
  email:
    recipients:
    - xukailu@baidu.com
    on_success: change
    on_failure: always

